# Generated by Django 3.0.6 on 2020-07-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amazon',
            fields=[
                ('aid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('aname', models.CharField(max_length=30)),
                ('aprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('catid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='flipkart',
            fields=[
                ('fid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=30)),
                ('fprice', models.IntegerField()),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('cname', models.CharField(max_length=30)),
                ('cmobile', models.CharField(max_length=10)),
                ('caddress', models.CharField(max_length=50)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.amazon')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flipkart')),
            ],
        ),
        migrations.AddField(
            model_name='amazon',
            name='catid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
